#!/usr/bin/env bash

set -e

ROOTDIR=$(git rev-parse --show-toplevel)
cd "$ROOTDIR"

make fmt

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.rs$|Cargo.toml$") || true)
files+=$((git diff --name-only | grep -Ei "Cargo.toml$") || true)
if [ ! -z "$files" ]; then
  echo "[cargo fmt] and [git add] the following files:"
  echo "$files"
  git add $(echo "$files" | paste -s -d " " -)
fi

