#!/usr/bin/env bash

set -e

ROOTDIR=$(git rev-parse --show-toplevel)
cd "$ROOTDIR"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.rs$") || true)
if [ ! -z "$files" ]; then
  echo "[cargo fmt] and [git add] the following files:"
  echo "$files"
  make fmt
  git add $(echo "$files" | paste -s -d " " -)
fi

