[package]
name = "id-itp-top-pool"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, features = ["net", "thread", "untrusted_time"], optional = true }

itc-direct-rpc-server = { package = "id-itc-direct-rpc-server", path = "../../core/direct-rpc-server", default-features = false }
itp-stf-primitives = { workspace = true }
itp-types = { workspace = true }
its-primitives = { workspace = true }

jsonrpc-core_sgx = { workspace = true, optional = true }
linked-hash-map_sgx = { workspace = true, optional = true }

jsonrpc-core = { workspace = true, optional = true }
linked-hash-map = { workspace = true, optional = true }

byteorder = { workspace = true }
codec = { package = "parity-scale-codec", workspace = true }
derive_more = { workspace = true }
log = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }

[dev-dependencies]
parity-util-mem = { workspace = true, features = ["primitive-types"] }
itp-test = { workspace = true }
serde = { workspace = true }
sp-application-crypto = { workspace = true }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "itc-direct-rpc-server/sgx",
    "jsonrpc-core_sgx",
    "linked-hash-map_sgx",
    # litentry
    "litentry-primitives/sgx",
]
std = [
    "itc-direct-rpc-server/std",
    "itp-types/std",
    "its-primitives/std",
    "jsonrpc-core",
    "linked-hash-map",
    "log/std",
    "serde/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-application-crypto/std",
    # litentry
    "litentry-primitives/std",
]
mocks = []
