[package]
name = "its-block-verification"
description = "Verification logic for sidechain blocks"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = "https://litentry.com/"
repository = "https://github.com/litentry/litentry-parachain"
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = { workspace = true }

thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

itp-types = { workspace = true }
itp-utils = { workspace = true }
its-primitives = { workspace = true }

frame-support = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

sgx_tstd = { workspace = true, features = ["untrusted_fs", "net", "backtrace"], optional = true }

[features]
default = ["std"]
std = [
    "log/std",
    "thiserror",
    "itp-types/std",
    "its-primitives/std",
    "frame-support/std",
    "sp-consensus-slots/std",
    "sp-core/std",
    "sp-runtime/std",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]

[dev-dependencies]
itc-parentchain-test = { workspace = true, features = ["std"] }
its-test = { workspace = true, features = ["std"] }
sp-keyring = { workspace = true }
