[package]
name = "id-itc-direct-rpc-server"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }

codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
sp-runtime = { workspace = true }

itc-tls-websocket-server = { workspace = true }
itp-rpc = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

jsonrpc-core = { workspace = true, optional = true }
jsonrpc-core_sgx = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    # no-std dependencies
    "codec/std",
    "log/std",
    "serde_json/std",
    "sp-runtime/std",
    # integritee dependencies
    "itp-types/std",
    # local
    "itc-tls-websocket-server/std",
    "itp-rpc/std",
    # optional ones
    "jsonrpc-core",
    "thiserror",
]
sgx = [
    "itc-tls-websocket-server/sgx",
    "itp-rpc/sgx",
    "jsonrpc-core_sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
mocks = []
