[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = "pallet-evm-precompile-aiusd-convertor"
version = '0.1.0'

[dependencies]
precompile-utils = { workspace = true }

# Substrate
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-aiusd-convertor = { workspace = true }
parity-scale-codec = { workspace = true, features = ["max-encoded-len"] }
scale-info = { workspace = true, features = ["derive"] }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Frontier
fp-evm = { workspace = true }
pallet-evm = { workspace = true, features = ["forbid-evm-reentrancy"] }

[dev-dependencies]
derive_more = { workspace = true }
hex-literal = { workspace = true }
libsecp256k1 = { workspace = true }
serde = { workspace = true }
sha3 = { workspace = true }
precompile-utils = { workspace = true, features = ["std", "testing"] }
pallet-timestamp = { workspace = true, features = ["std"] }
pallet-assets = { workspace = true }
pallet-balances = { workspace = true, features = ["std", "insecure_zero_ed"] }
parity-scale-codec = { workspace = true, features = ["max-encoded-len", "std"] }
scale-info = { workspace = true, features = ["derive"] }
sp-io = { workspace = true }
sp-runtime = { workspace = true, features = ["std"] }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-assets/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
]
std = [
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-aiusd-convertor/std",
    "pallet-evm/std",
    "pallet-timestamp/std",
    "precompile-utils/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
]
