[package]
name = "id-ita-parentchain-interface"
version = "0.1.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }

ita-sgx-runtime = { package = "id-ita-sgx-runtime", path = "../sgx-runtime", default-features = false }
ita-stf = { package = "id-ita-stf", path = "../stf", default-features = false }
itc-parentchain-indirect-calls-executor = { package = "id-itc-parentchain-indirect-calls-executor", path = "../../core/parentchain/indirect-calls-executor", default-features = false }
itp-api-client-types = { workspace = true }
itp-enclave-metrics = { workspace = true }
itp-node-api = { workspace = true }
itp-ocall-api = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-types = { workspace = true }

codec = { package = "parity-scale-codec", workspace = true }
log = { workspace = true }

sp-core = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
substrate-api-client = { workspace = true, optional = true }

lc-dynamic-assertion = { workspace = true }
lc-evm-dynamic-assertions = { workspace = true }
lc-omni-account = { workspace = true }
litentry-primitives = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
itp-node-api = { workspace = true, features = ["std", "mocks"] }
itp-sgx-crypto = { workspace = true, features = ["std", "mocks"] }
itp-test = { workspace = true }
itc-parentchain-test = { workspace = true }
itp-stf-executor = { package = "id-itp-stf-executor", path = "../../core-primitives/stf-executor", features = ["mocks"] }
itp-top-pool-author = { package = "id-itp-top-pool-author", path = "../../core-primitives/top-pool-author", features = ["mocks"] }


[features]
default = ["std"]
std = [
    "codec/std",
    "ita-sgx-runtime/std",
    "ita-stf/std",
    "itc-parentchain-indirect-calls-executor/std",
    "itp-api-client-types/std",
    "itp-node-api/std",
    "itp-sgx-crypto/std",
    "itp-stf-executor/std",
    "itp-stf-primitives/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "log/std",
    "sp-core/std",
    "sp-runtime/std",
    "substrate-api-client",
    "litentry-primitives/std",
    "lc-dynamic-assertion/std",
    "lc-evm-dynamic-assertions/std",
    "sp-std/std",
    "lc-omni-account/std",
]
sgx = [
    "sgx_tstd",
    "ita-stf/sgx",
    "itc-parentchain-indirect-calls-executor/sgx",
    "itp-node-api/sgx",
    "itp-sgx-crypto/sgx",
    "itp-stf-executor/sgx",
    "itp-top-pool-author/sgx",
    "litentry-primitives/sgx",
    "lc-dynamic-assertion/sgx",
    "lc-evm-dynamic-assertions/sgx",
    "lc-omni-account/sgx",
]
