[package]
name = "id-itc-direct-rpc-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
rustls_sgx = { workspace = true, features = ["dangerous_configuration"], optional = true }
sgx_tstd = { workspace = true, optional = true }
tungstenite_sgx = { workspace = true, optional = true }
webpki_sgx = { workspace = true, optional = true }

log = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

rustls = { workspace = true, features = ["dangerous_configuration"], optional = true }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"], optional = true }
webpki = { workspace = true, optional = true }

itp-rpc = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

[features]
default = ["std"]
sgx = [
    "webpki_sgx",
    "tungstenite_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "itp-rpc/sgx",
]
std = [
    "rustls",
    "webpki",
    "tungstenite",
    "url/std",
    "itp-rpc/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
]
