[package]
name = "itc-tls-websocket-server"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
bit-vec = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
rcgen = { workspace = true }

sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }

mio-extras = { workspace = true, optional = true }
mio_sgx = { workspace = true, optional = true }
rustls_sgx = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }
tungstenite_sgx = { workspace = true, optional = true }
webpki_sgx = { workspace = true, optional = true }
yasna_sgx = { workspace = true, optional = true }

mio = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tungstenite = { workspace = true, features = ["rustls-tls-webpki-roots"], optional = true }
webpki = { workspace = true, optional = true }
yasna = { workspace = true, features = ["bit-vec", "num-bigint", "chrono", "std"], optional = true }

sp-core = { workspace = true, features = ["full_crypto"] }

[dev-dependencies]
env_logger = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
url = { version = "2.0.0" }

[features]
default = ["std"]
sgx = [
    "mio-extras/sgx",
    "mio_sgx",
    "rcgen/sgx",
    "rcgen/pem_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "tungstenite_sgx",
    "webpki_sgx",
    "yasna_sgx",
]
std = [
    "mio",
    "mio-extras/std",
    "rcgen/std",
    "rcgen/pem",
    "rustls",
    "thiserror",
    "tungstenite",
    "webpki",
    "yasna",
    "log/std",
    "sp-core/std",
]
mocks = []
