services:
  demo-smart-contract:
    image: litentry-cli:${VERSION:-dev}
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
      - "${SGX_QCNL:-/dev/null}:/etc/sgx_default_qcnl.conf"
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      litentry-node-${VERSION}:
        condition: service_healthy
      litentry-worker-1-${VERSION}:
        condition: service_healthy
      litentry-worker-2-${VERSION}:
        condition: service_healthy
    environment:
      - RUST_LOG=warn,ws=warn,itc_rpc_client=warn
    networks:
      - litentry-test-network
    entrypoint:
      "/usr/local/worker-cli/demo_smart_contract.sh -p 9912 -u ws://litentry-node
      -V wss://litentry-worker-1 -A 2011 -C /usr/local/bin/litentry-cli 2>&1"
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge
